title: eDNA Expeditions Phase II
description: "eDNA Expeditions Phase II"
url: "http://127.0.0.1:4000"
baseurl: ""

# Do NOT specify a theme, this disables default themes
theme:

markdown: kramdown

include:
  - assets
  - css
  - js

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

destination: _site

kramdown:
  input: GFM
  hard_wrap: false

permalink: pretty